### ISSUE TITLE
Observable.observe_on should apply to all subsequent operators

### ISSUE THREAD

**Issue by JobNoorman** [ReactiveX/RxPY#117]
If in interpret the [ObserveOn](http://reactivex.io/documentation/operators/observeon.html) documentation correctly, the specified scheduler should be used for all subsequent operators. However, in the following code, `delay()` uses the default `TimeoutScheduler` to implement the delay (although it seems to be dispatched by the provided scheduler):

```
observable.observe_on(scheduler).delay(1000)
```

I think the call to `observe_on()` should somehow override the `scheduler` argument of `delay()` (and all other relevant operators).

On a related note: do we really need the `scheduler` argument in those operators? Shouldn't the `observe_on()` operator be enough for all use cases?

**Comment by dbrattli** [comment]
The documentation of ObserveOn only tells the observable notify observers on the specified scheduler and context. Thus your example will not work as delay will still get the default scheduler. But I think it's a very interesting idea that it should be used as the default scheduler for all subsequent operators. Especially when you want to use one particular scheduler for the pipeline such as asyncio etc. I'm flagging this as a feature request.

**Comment by adamples** [comment]
For me the real problem is that some operators switch to arbitrary scheduler implicitly, by default and even when it's not neccesary (I believie it's because the default scheduler is a blocking one). I don't think the proposed change can solve this issue, at least not for all use cases.

Please consider this: suppose I want to expose an rx-enabled function in my library. The function returns observable but also uses `delay` or `timeout` operator in the implementation:

    def a_wait_of_some_sort_with_timeout(data):
        return create_some_observable().filter(lambda x, _: x == data).take(1).timeout(1000)

As this is a general-purpose library I don't want to make any assumptions about scheduler(s) that user wants to employ.

Now for some reason the user doesn't want to spawn any threads. Instead they wan't to use just one scheduler, e.g. asyncio. But they can not alter the function behavior using `observe_on` -- `timeout` will switch scheduler anyway. So let's assume that the same functionality (of changing the default scheduler) is implemented in `subscribe_on`. Then if user chooses non-blocking scheduler everything is fine. But what will happen if a blocking-scheduler is chosen? Shall it still override the default for `timeout` operator? Or shall it switch to `TimeoutScheduler`? In the former case function will not work with blocking scheduler, and in the latter it will switch to arbitrary scheduler, which the user doesn't want.

Both options require me as a library provider to document that the function uses timeout operator and possibly to add some timeout_scheduler parameter to give user the full control. This way I fail to provide abstraction for my users, because I'm forcing them to be constantly aware of details of my implementation.

IMO the better solution for this use case would be for `timeout` to not switch scheduler unless it's 1) neccessary (i.e. the upstream scheduler is blocking) or 2) requested explicitly using `scheduler` parameter. This may seem like a very small difference, but I think it would make for a more consistent API for both RxPY and third-party libraries.

**Comment by MainRo** [comment]
Closing since this should be ok in v3. please re-open if needed.
