### ISSUE TITLE
`group_by()` doesn't work with Reducing Operators

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxPY#133]
I was working on some course material and then I noticed that using `group_by()` is not working with the `count()` operator. 

For instance, if I emit a sequence of letters and count their occurrences using `group_by()`, the counts are all short by 1. 

```python
from rx import Observable

Observable.from_("alphabetagammadeltaepsilon") \
    .group_by(lambda s: s) \
    .map(lambda grp: grp.count().map(lambda ct: "{0}-{1}".format(grp.key,ct))) \
    .merge_all() \
    .subscribe(print)
```

**OUTPUT:**

```
a-5
l-2
p-1
h-0
b-0
e-2
t-1
g-0
m-0
d-0
s-0
i-0
o-0
n-0
```

Even more unsettling is sometimes the counts just come out to zero when several occurrences do exist. 

```python
from rx import Observable

Observable.from_(["alpha", "apple", "beta", "bat", "gamma"]) \
    .group_by(lambda s: s[0]) \
    .map(lambda grp: grp.count().map(lambda ct: "{0}-{1}".format(grp.key, ct))) \
    .merge_all() \
    .subscribe(print)
```

**OUTPUT:**

```
a-0
b-0
g-0
```

I have confirmed RxJava does not have this problem. Interestingly though, not doing any reducing like `count()` or `to_list()` will result in no emissions being missed.

```python
Observable.from_(["alpha", "apple", "beta", "bat", "gamma"]) \
    .group_by(lambda s: s[0]) \
    .merge_all() \
    .subscribe(print)
```

**OUTPUT:**

```
alpha
apple
beta
bat
gamma
```

Is there something I am missing? Or is this a bug?

**Comment by thomasnield** [comment]
Interestingly I did not have this problem on my Linux machine last night. It might have been running an older version of RxPy.

**Comment by thomasnield** [comment]
Just rolled back to RxPy 1.5.2. Now it is working fine. It looks like 1.5.3 is broken.

**Comment by thomasnield** [comment]
This regression still exists with 1.5.4. For the given code below:

```python
from rx import Observable

Observable.from_("alphabetagammadeltaepsilon") \
    .group_by(lambda s: s) \
    .map(lambda grp: grp.count().map(lambda ct: "{0}-{1}".format(grp.key,ct))) \
    .merge_all() \
    .subscribe(print)
```

This is the output when ran with 1.5.2

```
a-6
l-3
p-2
h-1
b-1
e-3
t-2
g-1
m-2
d-1
s-1
i-1
o-1
n-1
```

But on 1.5.3 and 1.5.4, I get this output:

```
a-5
l-2
p-1
h-0
b-0
e-2
t-1
g-0
m-0
d-0
s-0
i-0
o-0
n-0
```

**Comment by thomasnield** [comment]
This issue seems to only occur when GroupedObservables are aggregated within a `flat_map()` or `merge_all()`, such as `count()` and `to_list()`. Oddly, the `to_list()` will yield empty Lists. 

```python
from rx import Observable

Observable.from_(["alpha", "apple", "beta", "bat", "gamma"]) \
    .group_by(lambda s: s[0]) \
    .map(lambda grp: grp.to_list()) \
    .merge_all() \
    .subscribe(print)
```
**OUTPUT:**

```
[]
[]
[]
```

**Comment by dbrattli** [comment]
Sorry closed this by accident. But fix have been made, so please test if the problem still exist with 1.5.5. One of the hardest problems I have debugged in a long time, but basically the the problem was that there was a race between the `on_next()` of `from_iterable()` with the subscribing of the inner subscription in `merge()`. The operator `group_by()` creates a `Subject` (the group) and will `on_next()`the group and then `on_next()` the value into the group. But someone needs to subscribe to the group before you `on_next()` or the value will be lost. The subscribe chain went through the `concat()` operator that was scheduling using `current_thread_scheduler` and that meant that the subscribe would be done after what was currently happening, thus the `on_next()` would happen before `subscribe()`. Hopefully things will work as expected now.

**Comment by thomasnield** [comment]
Awesome, thank you so much for debugging this so quickly. I ran all my tests that I was having issues with, and everything looks to be resolved.
