### ISSUE TITLE
Questions about concurrency

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxPY#135]
Hey Dag, I have a few final questions before I finalize my material for the video shoot on Tuesday. Thanks again for all your responsiveness and help. I think RxPy is going to be helpful for a lot of folks I am speaking to. 

**QUESTION 1:**

In [Java Concurrency in Practice](http://a.co/4ZHIpUD ), Goetz says that for computation-intensive tasks, a roughly optimal thread pool size is _(# of CPU Cores) + 1_. I am guessing that when creating a `ThreadPoolScheduler` to support computation-intensive processes, this rule-of-thumb is still valid? 

```python
# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)
```

**QUESTION 2:**

Coming from RxJava, I noticed that `subscribe_on()` will take one thread from a `ThreadPoolScheduler` as expected.

```python
from rx import Observable
from rx.concurrency import ThreadPoolScheduler
from threading import current_thread
import multiprocessing, time, random


def intense_calculation(value):
    # sleep for a random short duration between 0.5 to 2.0 seconds to simulate a long-running calculation
    time.sleep(random.randint(5,20) * .1)
    return value

# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

# Create Process 1
Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"]) \
    .subscribe_on(pool_scheduler) \
    .map(lambda s: intense_calculation(s)) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!"))

input("Press any key to quit\n")
```

**OUTPUT:**

```
Press any key to quit
PROCESS 1: Thread-1 Alpha
PROCESS 1: Thread-1 Beta
PROCESS 1: Thread-1 Gamma
PROCESS 1: Thread-1 Delta
PROCESS 1: Thread-1 Epsilon
PROCESS 1 done!
```

However, `observe_on()` behaves quite differently in how it claims threads. I understand that `observe_on()` will redirect emissions to a different scheduler _at that point_ in the `Observable` chain, but I noticed it may use a different thread for each emission. 

```python
from rx import Observable
from rx.concurrency import ThreadPoolScheduler
from threading import current_thread
import multiprocessing, time, random


def intense_calculation(value):
    # sleep for a random short duration between 0.5 to 2.0 seconds to simulate a long-running calculation
    time.sleep(random.randint(5,20) * .1)
    return value

# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

# Create Process 1
Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"]) \
    .observe_on(pool_scheduler) \
    .map(lambda s: intense_calculation(s)) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!"))

input("Press any key to quit\n")
```

**OUTPUT:**

```
Press any key to quit
PROCESS 1: Thread-1 Alpha
PROCESS 1: Thread-2 Beta
PROCESS 1: Thread-1 Gamma
PROCESS 1: Thread-3 Delta
PROCESS 1: Thread-2 Epsilon
PROCESS 1 done!
```

Is this expected? In RxJava, `subscribeOn()` and `observeOn()` will both only claim one thread for each subscription. I don't see an issue with `observe_on()` using multiple threads for  a single subscription as long as the Observable contract still being adhered to and the emissions stay serialized. Is this the behavior you intended by design?

**Comment by dbrattli** [comment]
See answers inline

--
Dag Brattli



On 27. november 2016 at 18.09.45, Thomas Nield (notifications@github.com<mailto:notifications@github.com>) wrote:

hey Dag, I have a few final questions before I finalize my material for the video shoot on Tuesday. Thanks again for all your responsiveness and help. I think RxPy is going to be helpful for a lot of folks I am speaking to.

QUESTION 1:

In Java Concurrency in Practice<http://a.co/4ZHIpUD>, Goetz says that for computation-intensive tasks, a roughly optimal thread pool size is (# of CPU Cores) + 1. I am guessing that when creating a ThreadPoolScheduler to support computation-intensive processes, this rule-of-thumb is still valid?

# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

I would guess so, but Python is a very different land than Java. In Python there is the infamous GIL that restricts  a single thread to execute Python code at any moment in time. The only place you can do computation-intensive work is in extension libraries (where the GIL is released) like NumPY etc.

QUESTION 2:

Coming from RxJava, I noticed that subscribe_on() will take one thread from a ThreadPoolScheduler as expected.

from rx import Observable
from rx.concurrency import ThreadPoolScheduler
from threading import current_thread
import multiprocessing, time, random


def intense_calculation(value):
    # sleep for a random short duration between 0.5 to 2.0 seconds to simulate a long-running calculation
    time.sleep(random.randint(5,20) * .1)
    return value

# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

# Create Process 1
Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"]) \
    .subscribe_on(pool_scheduler) \
    .map(lambda s: intense_calculation(s)) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!"))

input("Press any key to quit\n")

OUTPUT:

Press any key to quit
PROCESS 1: Thread-1 Alpha
PROCESS 1: Thread-1 Beta
PROCESS 1: Thread-1 Gamma
PROCESS 1: Thread-1 Delta
PROCESS 1: Thread-1 Epsilon
PROCESS 1 done!


However, observe_on() behaves quite differently in how it claims threads. I understand that observe_on() will redirect emissions to a different scheduler at that point in the Observable chain, but I noticed it may use a different thread for each emission.

from rx import Observable
from rx.concurrency import ThreadPoolScheduler
from threading import current_thread
import multiprocessing, time, random


def intense_calculation(value):
    # sleep for a random short duration between 0.5 to 2.0 seconds to simulate a long-running calculation
    time.sleep(random.randint(5,20) * .1)
    return value

# calculate number of CPU's and add 1, then create a ThreadPoolScheduler with that number of threads
optimal_thread_count = multiprocessing.cpu_count() + 1
pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

# Create Process 1
Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"]) \
    .observe_on(pool_scheduler) \
    .map(lambda s: intense_calculation(s)) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!"))

input("Press any key to quit\n")

OUTPUT:

Press any key to quit
PROCESS 1: Thread-1 Alpha
PROCESS 1: Thread-2 Beta
PROCESS 1: Thread-1 Gamma
PROCESS 1: Thread-3 Delta
PROCESS 1: Thread-2 Epsilon
PROCESS 1 done!


Is this expected? In RxJava, subscribeOn() and observeOn() will both only claim one thread for each subscription. I don't see an issue with observe_on() using multiple threads as long as the Observable contract still being adhered to and the emissions stay serialized. Is this the behavior you intended by design?

Hi, it is not intended by design, and I was a bit surprised since I cannot reproduce it on my Mac. Tried Linux, and not I see the “unexpected” behavior. But I have rechecked, and it is by design. The ThreadPoolScheduler will be given a free thread to run this subscription on, but it will not stick the thread to the subscription. If there are possibly overlapping events then the second will be put on the EventLoopScheduler on the same thread as the one before. When the subscription becomes idle, then the thread will stop, and the next event might not get the same thread as the previous events.

The safer option is to run from_() on the thread pool (without observe_on)

# Create Process 1

Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"], pool_scheduler) \

    .map(lambda s: intense_calculation(s)) \

    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),

               on_error=lambda e: print(e),

               on_completed=lambda: print("PROCESS 1 done!”))

To explain this, the ThreadPoolScheduler will possibly get a new thread for each scheduled action. If the scheduled action schedules an action, then that (sub)action will be run on the same thread as the parent action. Thus for observe_on(), the first event will run on a new thread, the next events might run on the same thread if they are sent before the first one is finished (to avoid overlap). If things are idle, then the OS decides which thread they will get.

For from_(.., scheduler), the pumping of events is scheduled, and the second (and beyond) items will be sub-actions, so they are forced to be on the same thread.

For “parallel” execution you would need to use select_many/flat_map to spawn new subscriptions on separate threads:


# Create Process 1

Observable.from_(["Alpha", "Beta", "Gamma", "Delta", "Epsilon"]) \

    .flat_map(lambda s: Observable.just(s, pool_scheduler).map(lambda s: intense_calculation(s))) \

    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),

               on_error=lambda e: print(e),

               on_completed=lambda: print("PROCESS 1 done!"))

DB

**Comment by AXGKl** [comment]
@thomasnield : "material for the video shoot on Tuesday." sounds interesting, will this content be somehow accessible?

**Comment by thomasnield** [comment]
@AXGI Yeah,  I just flew into San Francisco. Tomorrow I'm creating a 3 hour training video with OReilly called "Reactive Python for Data". I'm somewhat leaning content towards data analysis but I think any programmer wanting to learn RxPy will find it helpful.

The video should be live in a few weeks after it is shot tomorrow. I'll post on this thread when it's up. 

@dbrattli thank you Dag, I'll go through your notes tonight. Thanks again for all your assistance.

**Comment by thomasnield** [comment]
@dbrattli okay, I may make some last minute tweaks with your input. Thank you.

**Comment by AXGKl** [comment]
@thomasnield : good luck for the shot - and the topic is just perfect !

**Comment by thomasnield** [comment]
@AXGKI thanks! I'll keep you posted.

**Comment by dbrattli** [comment]
### QUESTION 1:
I would guess so, but Python is a very different land than Java. In Python there is the infamous GIL that restricts  a single thread to execute Python code at any moment in time. The only place you can do computation-intensive work is in extension libraries (where the GIL is released) like NumPY etc.

### QUESTION 2:
It is not intended by design, and I was a bit surprised since I cannot reproduce it on my Mac. Tried Linux, and not I see the “unexpected” behavior. But I have rechecked, and it is by design. The `ThreadPoolScheduler` will be given a free thread to run this subscription on, but it will not stick the thread to the subscription. If there are possibly overlapping events then the second event will be put on the `EventLoopScheduler` on the same thread as the one before. `ThreadPoolScheduler` is really a `NewThreadScheduler` with an `EventLoopScheduler` for each thread. When the subscription becomes idle, then the thread will exit, and it's up to the runtime to decide if the next event might not get the same thread as the previous events.

The safer option is to run from_() on the thread pool (without observe_on)

```python
Observable.from_(["Alpha","Beta","Gamma","Delta","Epsilon"], pool_scheduler) \
    .map(lambda s: intense_calculation(s)) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!”))
```

To explain this, the `ThreadPoolScheduler` will possibly get a new thread for each scheduled action. If the scheduled action schedules an action, then that (sub)action will be run on the same thread as the parent action. Thus for `observe_on()`, the first event will run on a new thread, the next events might run on the same thread if they are sent before the first one is finished (to avoid overlap). If things are idle, then the OS decides which thread they will get.

For `from_(.., scheduler)`, the pumping of events is scheduled, so the second (and beyond) items will be sub-actions, so they are forced to be on the same thread.

For “parallel” execution you would need to use `select_many/flat_map` to spawn new subscriptions on separate threads:

```python
Observable.from_(["Alpha", "Beta", "Gamma", "Delta", "Epsilon"]) \
    .flat_map(lambda s: Observable.just(s, pool_scheduler).map(lambda s: intense_calculation(s))) \
    .subscribe(on_next=lambda i: print("PROCESS 1: {0} {1}".format(current_thread().name, i)),
               on_error=lambda e: print(e),
               on_completed=lambda: print("PROCESS 1 done!"))
```

**Comment by thomasnield** [comment]
Thanks @dbrattli. I finished the video shoot today with O'Reilly. It went great and should be live in a few weeks. I apologize in advance if I skipped over topics and the different flavors to do a task. For instance, I taught `subscribe_on()` and `observe_on()` but didn't show the option to specify a scheduler at the source factory. I was trying to take an API approach where you may not have access to the source `Observable`.

I was also trying to simplify the content somewhat and make it accessible. I do hope this takes off and data science folks find value in RxPy. You've created something great that might be of great value to them.

**Comment by thomasnield** [comment]
@AXGKl if you have an O'Reilly Safari subscription, my webcast "Reactive Python for Data Science" is now open for registration (this will air quarterly). The recorded videos are also coming anytime now. 

https://www.safaribooksonline.com/live-training/courses/reactive-python-for-data-science-production-ready-scalable-code-for-real-time-data/0636920068839/

**Comment by AXGKl** [comment]
@thomasnield : Wow, what an agenda. It'll be February 21, 2017 and I subscribed right now ;-)

**Comment by thomasnield** [comment]
@AXGKI I'm glad you're as excited as I am, and I'm glad you are attending. Let others know too because although I've already got four sessions this year,  I'd love to get a full attendance. A strong interest would allow more content and mediums on RxPy to be developed.

**Comment by thomasnield** [comment]
@AXGKl On-demand video course is now live https://www.safaribooksonline.com/library/view/reactive-python-for/9781491979006/

**Comment by AXGKl** [comment]
@thomasnield : Watched it all - what a treat!! You start from scratch and get slowly but steadily to point where I totally learned new stuf and I had already invested quite some time into RX.

@dbrattli : Not that I'm relevant but I'm pretty convinced that this is **by far** the best way to get beginners up and running with RX, would deserve a prominent link in the Readme, in my opinion.

**Comment by thomasnield** [comment]
@AXGKI thank you that means a lot to me : ) I hope to do more stuff like this and am hoping Rx will be used everywhere inside and outside data science. 

@dbrattli I hate to self-promote,  but that would be an honor if you find the course fitting to list as a resource : )
