### ISSUE TITLE
How to do unit test when use rx.Ob

### ISSUE THREAD

**Issue by GrapeBaBa** [ReactiveX/RxPY#153]
Source code:
```python
    def async_get_value(self, key, scheduler=None):
        """Get a value with a specific key.

        :param scheduler: scheduler
        :param key: key

        :return:a future object
        """
        return rx.Observable.start(lambda: self.get_value(key), scheduler)
```

Test code:
```python
    def test_async_write_and_read(self):
        """Test for async setting and getting."""
        key_value_store = file_key_value_store(self.path)
        key_value_store.async_set_value(self.key, self.value) \
            .flat_map(lambda x: key_value_store.async_get_value(self.key)) \
            .subscribe(rx.AnonymousObserver(
                lambda x: self.assertEqual(x, self.value)))
```
This test is always correct, I wonder how to test this async method

**Comment by dbrattli** [comment]
If you want it to fail then setup your test so that  `self.get_value(key)` throws an exception. It it's an async operation, then it should be possible that it might fail?

**Comment by GrapeBaBa** [comment]
@dbrattli Actually I want to check the x == self.value, but after I test, if i change to self.assertEqual(x,""), the test still success. I want to know how to test this case.

**Comment by dbrattli** [comment]
Your current test uses an `AnonymousObserver` that swallows all errors since you only impl. the `on_next()` which will probably not be executes at all in case of error. You should use the `TestScheduler`. The `start()` method creates a `MockObserver` that records all events and makes it easier to test. See some of the tests. Check out https://github.com/ReactiveX/RxPY/blob/master/tests/test_observable/test_toasync.py for an example.

**Comment by GrapeBaBa** [comment]
@dbrattli thanks. I am not quite the default scheduler TimeoutScheduler, it doesn't need a time to create. How does it judge if timeout?

**Comment by dbrattli** [comment]
Make sure the test uses the `TestScheduler`, and supply that scheduler to all operators that takes scheduler as a parameter.
