### ISSUE TITLE
Wait for thread pool to finish

### ISSUE THREAD

**Issue by florian-jackisch** [ReactiveX/RxPY#203]
The example on the README about using the thread pool calls `input("Press any key to quit\n")` to halt the execution. Is there a way to wait for the execution of the streams to finish, even when they run in a different thread?

**Comment by thomasnield** [comment]
I'll need to review how RxPY presents it, but you will need to use a blocking operator. We might want to add a `blocking_subscribe()` if one doesn't exist already. But look at the blocking operators for now...

**Comment by gpcimino** [comment]
Hi all,

can anybody provide a working example with thread pool and a blocking operator to avoid having  `input("Press any key to quit\n")` at the end of the script.

Thanks a lot!

**Comment by shyam-s00** [comment]
Ok, I'm new to RxPy and I'm, not sure if this is the right approach, but I saw something similar done in one of the blocking operator. 

Probably some one can suggest a better way of doing this. 

```
from rx import Observable
from rx.concurrency import ThreadPoolScheduler
from rx import config
from rx.internal import extensionmethod
import multiprocessing

class Example:
    
    def __init__(self):
        self.latch = config['concurrency'].Event()

    def printsequence(self):    
        def on_completed():
            print('Completed...')
            self.latch.set()

        optimal_thread_count = multiprocessing.cpu_count()
        pool_scheduler = ThreadPoolScheduler(optimal_thread_count)

        Observable.from_(range(10)) \
            .zip(Observable.interval(1000), lambda x,y: x) \
            .subscribe_on(pool_scheduler) \
            .subscribe(print, print, on_completed)
        
        self.latch.wait()

if __name__ == '__main__':
    Example().printsequence()
    
```

**Comment by gpcimino** [comment]
@shyam-s00 ,

thanks a lot it works!

however, i would expect to do it with less code! 
For instance, i like the idea of  `blocking_subscribe() `as @thomasnield  suggested. 

Thanks again
GP

**Comment by Hong-Xiang** [comment]
I'm facing the sample problem. However I need to mix reactive and directives together, thus I'm facing the block problem frequently, @shyam-s00 's solution seems too long for me to use in many helper functions.

Actually I'm using RxPy as an functional programming library for its clear design and awesome way of calling functions by dot chained operators. 

The following is a example of codes:

``` python
def find_something(inputs_) -> Observable:
  return (rx.Observable.from_(inputs_, 
                              scheduler=rx.concurrency.ThreadPoolScheduler())
                       .filter(some_filter1)
                       .map(lambda x: foo(x))
                       .filter(some_filter2)
)

def some_func_accepts_iterable(inputs_: Iterable[str]):
    return [func2(s) for s in inputs_]

def caller(inputs_):
    result = find_something(inputs_).to_list().to_block().first()
    return some_func_accepts_iterable(result)
```

There are two prblems:

Nested block problem
---
First one is related to [#182](https://github.com/ReactiveX/RxPY/issues/182), I can not use the default scheduler since I don't know if the `inputs_` used `to_block()`. Even when `inputs_` is an iterable like list or tuple, it could be an result of `.to_list().to_block().first()`, there is still risk of nested blocking.
`rx.concurrency.ThreadPoolScheduler` currently works fine, but I'm wondering if there would be problem when depth of nested blocks is larger than maximum number of threads.

Good way of block/subscribe `Observable`
---
The second problem is that I used `.to_list().to_blocking().first()` every where, it seems not a good practice, however as mentioned by @thomasnield and @shyam-s00 , there is no something like `blocking_subscribe()`, I don't know if there is better way to do this. 

I've also tested some codes like:
``` python
def block_a_observable(a: Observable):
    result = []
    a.subscribe(result.append)
    return result
```
But I think this is not safe solution, there seems to be many cases while this function returns empty list.

Do you have suggestions for best practice of using RxPy in these two problems?

Thanks.

**Comment by shyam-s00** [comment]
If the existence blocking_subscribe() will make things simpler for you guys, you can try something like this and use it instead of the normal subscribe.  

```
@extensionmethod(BlockingObservable)
def blocking_subscribe(source, on_next = None, on_error = None, on_completed = None):
    latch = config['concurrency'].Event()

    def onNext(src):
        if on_next:
            on_next(src)
    
    def onError(src):
        if on_error:
            on_error(src)
        latch.set()

    def onCompleted():
        if on_completed:
            on_completed()
        latch.set()

    disposable = source.subscribe(onNext, onError, onCompleted)
    latch.wait()

    return disposable
```

**Comment by gpcimino** [comment]
@shyam-s00  looks good!
Why you don't make a pull request? 
It would be nice to have this feature in the main code repository!
GP

**Comment by dbrattli** [comment]
Master branch has a blocking `run()` i.e `result = source.run()` that will return the last value emitted from the observable. To get all the values pipe through the `to_iterable()` operator first.
