### ISSUE TITLE
RxPY community forum?

### ISSUE THREAD

**Issue by vegabook** [ReactiveX/RxPY#212]
Apologies if this is not quite the right forum, but as somebody completely new to ReactiveX, I'm wondering how to get active help on RxPY using Slack, IRC, Gitter, Discourse, or equivalent. I can't seem to find anything and am having trouble getting decent answers on Stack Overflow:

https://stackoverflow.com/questions/46879555/how-to-use-rxpy-or-rxjs-combine-latest-with-a-group-by-observable

https://stackoverflow.com/questions/46876527/in-reactivex-how-do-i-pass-other-parameters-to-observer-create

By contrast I'm finding the RxJS community to be very active (I guess Angular is a big part of that), and they're helping me once in a while on Gitter, but it's imperfect as modern JS is becoming more and more "functional" and the solutions in JS don't always map well to Python. 

Is there any RxPY community online? Is there any interest to create one? Personally happy to get involved but I need to get properly up to speed first on what I consider to be an amazing, and strategic, technology which should be much more widespread in data science. 

BTW I loved Thomas Neald's videos, and have all the sample code, but unfortunately my 10-day Safari trial has ended. I'm waiting in anticipation of the Python Reactive Programming book from Packt which I have already pre-ordered.

**Comment by thomasnield** [comment]
Hi @vegabook, I'm glad you like the video, thank you. This is something I'd definitely like to support although I don't have a definite answer on what will work best. 

Here are some thoughts: 

[Kotlin](https://kotlinlang.org/) has a phenomenal support community as well, with it's own [Slack channel](https://kotlinlang.slack.com/) and active community. Granted, they have a dedicated JetBrains team which kept the momentum going until critical community mass was reached. There is even an #rx channel which is active daily with RxJava/RxKotlin questions and answers.

It would be best to find an existing (and highly active) Slack Python community that's similar and add an #rx channel to it effectively. I don't know if such a community exists though, and the next best things I can think of are the [Python Forum](https://python-forum.io/Forum-General-Coding-Help) and [Reddit](https://www.reddit.com/r/Python/). 

So I think putting together a Slack is a great idea, but it'd be better if we could piggyback as a channel to a dedicated Python Slack, rather than an entire RxPy Slack domain.

**Comment by thomasnield** [comment]
this looks promising. 

https://pyslackers.com/

**Comment by thomasnield** [comment]
I joined PySlackers and asked the folks there if we could create an #rx channel. I'll be surprised if they push back. 

The community looks to be pretty large and active. 
https://www.reddit.com/r/Python/comments/6yh5uy/python_slack_community_pyslackers_8500_users/

**Comment by thomasnield** [comment]
Alright, we are set with PySlackers. The maintainers have graciously given us our own channel. 

I added a section to the README with instructions on where to join. 

https://github.com/ReactiveX/RxPY#community

@dbrattli I hope it was okay I took the liberty to do this. This hopefully will take pressure off the GitHub issues. 

I hope everyone gets an opportunity to join PySlackers. I'll see you in the #rxpy channel.

**Comment by vegabook** [comment]
Fantastic. As I said, I will be happy to try and help to move the awareness of PyRX and to "man" the channel, but I am completely new to it for now so I'll need at least a few weeks to get up to speed. I'm toying with the idea of staring a "adventures learning PyRX" blog of some kind. Keep you posted on PySlackers/RxPY!

**Comment by thomasnield** [comment]
@vegabook awesome! Please keep us posted.
