### ISSUE TITLE
QObject::startTimer: Timers can only be used with threads started with QThread

### ISSUE THREAD

**Issue by philipbel** [ReactiveX/RxPY#233]
Hello.

I am trying to use QtScheduler in conjunction with ThreadPoolScheduler, the idea being to perform network operations in background threads, and then to call back into the UI.

```python
do_something() \
    .subscribe_on(tpsch) \
    .observe_on(qtsch) \
    .subscribe(on_next=on_content_received,
                on_error=lambda e: print("error: {}".format(e)),
                on_completed=lambda: print("completed"))
```

I get this error from `_qtimer_schedule`:
```
QObject::startTimer: Timers can only be used with threads started with QThread
```

Please, see [this gist](https://gist.github.com/philipbel/a64bcc11114f1685086b61c9d5490a5b) for a test case.

Is this behavior expected?

**Comment by benjaminHanalytics** [comment]
any solutions?

**Comment by jcafhe** [comment]
Hello,
better late than never, the QtScheduler can not be 'mixed' with schedulers that schedule elements on an other thread than the Qt thread. This is because QtScheduler is based on QTimer which is not thread safe and cannot be started from another thread.

So you have to specify for each operator in your chain that accepts a scheduler as argument your QtScheduler. In RxPY3 (wip), you will specify the desired scheduler in `subscribe` method for all the upstream chain. This is decribed [here](https://github.com/ReactiveX/RxPY/issues/285#issuecomment-458431770).

Alternatively, I've been working on a QtScheduler which should be thread safe. It's available here:
https://github.com/jcafhe/RxPY/tree/qt-threadsafe 
It defines a new scheduler in `rx.concurrency.mainloopscheduler.qtthreadsafe` which is based on `QtCore.QCoreApplication.postEvent()`. There are some examples in rx/examples/qtthreadsafe. Keep in mind it's just a prototype and may be out of date but please feel free to improve it.

**Comment by wuyuanyi135** [comment]
@jcafhe Thank you. Your thread-safe version of QtScheduler works well. Can you please elaborate what "thread-safe" means in the context of rx? I ran into the similar problem of `AsyncioThreadSafeScheduler` and `AsyncioScheduler` before.
