### ISSUE TITLE
Subjects and ThreadPoolScheduler Question

### ISSUE THREAD

**Issue by avikaza** [ReactiveX/RxPY#268]
Thanks in advance.

I have an existing application where I am trying to slowly start bringing in RxPy and I have a confusion with regard to subscribe_on(ThreadPoolScheduler) when used with a Subject (I am using a Subject in order to do an on_next after subscription).

I understand ideally I should be creating a hot observable instead of doing an on_next on Subject after subscription like this but that will mean re-writing a bigger chunk of code.

```
...
cpu_cnt = multiprocessing.cpu_count()
pool_scheduler = ThreadPoolScheduler(cpu_cnt)

process_one_subject = Subject()
process_two_subject = Subject()

process_one_subject \
        .subscribe_on(pool_scheduler) \
        .subscribe(on_next=lambda msg: p1_handler(msg))

process_two_subject \
        .subscribe_on(pool_scheduler) \
        .subscribe(on_next=lambda msg: p2_handler(msg))


def p1_handler(msg):
    print('{0} {1} started p1: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(3)
    print('{0} {1} finished p1: {2}'.format(os.getpid(), current_thread().name, msg))

def p2_handler(msg):
    print('{0} {1} started p2: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(5)
    print('{0} {1} finished p2: {2}'.format(os.getpid(), current_thread().name, msg))

def process_function(subj, msg):
    subj.on_next(msg)

def main():
    start = time.time()
    for i in range(0, 5):
        process_one_subject.on_next(i)
        process_two_subject.on_next(i)
    end = time.time()
    print(end - start)
```
Q1: I was expecting that processes use multiple threads (atleast one per subscription) to handle the work but everything works on the main thread. 

Q2: Are there plans to create ProcessPoolScheduler from multiprocessing.Pool? Because it is better to use sub-process based pools primarily for CPU intensive operations.

**Comment by jcafhe** [comment]
Hi,
I'm not 100% sure but I think subscribe_on() does not work with hot observables. 

Basically, this operators means :
at the time of the subscription i.e. when calling the operator subscribe(on_next=...), you want that the upstream source starts to generate and emit data in the specified thread. In other words, the subscription triggers the emission of data from the source in the specified thread.

In your example, subscribe_on() does nothing since the start and the rate of emission is 'controlled' by you calling subject.on_next() in the main thread, so the downstream subscription triggers nothing. Your subject is hot.

In the contrary, if you use a cold observable like rx.Observable.range(0, 5) or rx.Observable._from([0, 1, 2, 3, 4]), it works:
```python
# -*- coding: utf-8 -*-
import os
import time
import multiprocessing
from threading import current_thread
import rx

cpu_cnt = multiprocessing.cpu_count()
pool_scheduler = rx.concurrency.ThreadPoolScheduler(cpu_cnt)

# cold observable that generates 0-5
numbers = rx.Observable.range(0, 5)

def p1_handler(msg):
    print('{0} {1} started p1: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(3)
    print('{0} {1} finished p1: {2}'.format(os.getpid(), current_thread().name, msg))


def p2_handler(msg):
    print('{0} {1} started p2: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(5)
    print('{0} {1} finished p2: {2}'.format(os.getpid(), current_thread().name, msg))


numbers \
        .subscribe_on(pool_scheduler) \
        .subscribe(on_next=p1_handler)

numbers \
        .subscribe_on(pool_scheduler) \
        .subscribe(on_next=p2_handler)

time.sleep(16)
```


When dealing with hot observables, you should use the operator observe_on() instead, which will 'route' data on an other thread.

```python
# -*- coding: utf-8 -*-

import os
import time
import multiprocessing
from threading import current_thread

from rx.concurrency import ThreadPoolScheduler
from rx.subjects import Subject

cpu_cnt = multiprocessing.cpu_count()
pool_scheduler = ThreadPoolScheduler(cpu_cnt)

process_one_subject = Subject()
process_two_subject = Subject()

process_one_subject \
        .observe_on(pool_scheduler) \
        .subscribe(on_next=p1_handler)

process_two_subject \
        .observe_on(pool_scheduler) \
        .subscribe(on_next=p2_handler)


def p1_handler(msg):
    print('{0} {1} started p1: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(3)
    print('{0} {1} finished p1: {2}'.format(os.getpid(), current_thread().name, msg))


def p2_handler(msg):
    print('{0} {1} started p2: {2}'.format(os.getpid(), current_thread().name, msg))
    time.sleep(5)
    print('{0} {1} finished p2: {2}'.format(os.getpid(), current_thread().name, msg))


if __name__ == '__main__':
    for i in range(0, 5):
        process_one_subject.on_next(i)
        process_two_subject.on_next(i)
        time.sleep(16)
```

Keep in mind that in this example, 0 to 4 are send 'immediatly' in the for loop, the iteration are not blocked, so you have to maintain the main thread alive. 

Note that when you have a cold observable, it exists one stream 'instance' per subscription. If you have 2 subscriptions, the whole stream will be executed twice. That's not always what you want especially if you have heavy computations.

**Comment by avikaza** [comment]
Thank you @jcafhe that is very helpful
