### ISSUE TITLE
Prefer nonlocal or array in closure

### ISSUE THREAD

**Issue by erikkemperman** [ReactiveX/RxPY#296]
I sometimes find code like this

```python
foo = [0]
def fun():
  foo[0] = 1
```

but also like this

```python
foo = 0
def fun():
  nonlocal foo
  foo = 1
```

Any reason to prefer one or the other, in general, when I write new code, or tweak existing stuff? I like the second, but perhaps there's considerations I am not thinking of.

@dbrattli Sorry, by the way, for spamming you like this... I understand it might be annoying. Please feel free to close issues like this one straight away, they're not really interesting for anyone else.

For what it is worth, I feel I am almost ready to contribute something back!

**Comment by jcafhe** [comment]
Hi,

I think it comes from the time when both python 2 and 3 was supported (`nonlocal` was not available in py2).

Otherwise, I've seen one time in Rx code (can't remember where) that it was used to assure thread safety. Because of the GiL in cpython, `x[0] = value` is atomic. Therefore, it's not recommended.

**Comment by erikkemperman** [comment]
I guess this is resolved, let’s prefer nonlocal and change it when rencountering the array style?
