### ISSUE TITLE
Cannot filter multiple values

### ISSUE THREAD

**Issue by obiben** [ReactiveX/RxPY#341]
I'm trying to sample a hot observable every second for every symbol I am watching:

```python
import rx
from rx.subjects import Subject
level1_observable = Subject()
symbols = ['BMO.CA', 'TD.CA']

def handle_level1(channel, data):
    l1 = L1.decode(data)
    level1_observable.on_next(l1)

def matches(level1, symbol):
    print('matching {} with {}'.format(level1.Symbol, symbol))
    return level1.Symbol == symbol

for symbol in symbols:
    sub = level1_observable.filter(lambda l1: matches(l1, symbol)).sample(1000).subscribe(on_next_level1)
```

Once `handle_level1` starts getting called, `matches` compares all values to the last symbol in the list (in this snippet, 'TD.CA'). Is this supposed to work?

**Comment by jcafhe** [comment]
Hi,

I don't fully understand your code, but I think your problem comes from the fact that in python, you should **never** capture a reference in a lambda expression nested into a `for` loop.  This results in capturing only the last value of the iteration.

Instead, you should use a higher order function:

```python

def make_matches(symbol): 
   return lambda l1: matches(l1, symbol)

for symbol in symbols:
    sub = level1_observable.filter(make_matches(symbol)).sample(1000).subscribe(on_next_level1)
```
Alternatively, you can do the same thing with a double lambda inline but it's a bit fuzzy.

**Comment by obiben** [comment]
You're right, I've fixed the problem using a keyword parameter on my filtering lambda:
```
for symbol in watched:
    level1_observable.filter(lambda l1, symbol=symbol: l1.Symbol == symbol).sample(1000).subscribe(on_next_level1)
```
about an hour ago, but didn't think to update and close this here, since I've immediately stumbled on another unrelated issue. Thanks
