### ISSUE TITLE
Enforce CurrentThreadScheduler to run on a dedicated thread?

### ISSUE THREAD

**Issue by MichaelSchneeberger** [ReactiveX/RxPY#358]
I have two concerns about the `rx.concurrency.currentthreadscheduler.CurrentThreadScheduler` class implementation. Both relate to the `__new__` method:

``` python
    def __new__(cls) -> 'CurrentThreadScheduler':
        """Ensure that each thread has at most a single instance."""

        thread = threading.current_thread()
        self: 'CurrentThreadScheduler' = CurrentThreadScheduler._global.get(thread)
        if not self:
            self = super().__new__(cls)
            CurrentThreadScheduler._global[thread] = self
        return self
```

**1.** Is a `CurrentThreadScheduler` always supposed to schedule actions on the same thread? In my opinion, the `CurrentThreadScheduler` is attached to some thread once the trampoline is run for the first time or "reactivated".

**2.** When I tried to extend from `CurrentThreadScheduler` in [rxbackpressure](https://github.com/MichaelSchneeberger/rxbackpressure) I couldn't do it because the `__new__` method would always return a `CurrentThreadScheduler`.

``` python
class MyCurrentThreadScheduler(SchedulerMixin, CurrentThreadScheduler):
    pass

my_current_thread_scheduler = MyCurrentThreadScheduler()
print(type(my_current_thread_scheduler))     # would print CurrentThreadScheduler
```

**Comment by erikkemperman** [comment]
My understanding of the semantics of CurrentThreadScheduler is that the same thread which invokes the schedule method should also invoke the scheduled callback.

This is independent of which thread _created_ the scheduler. So even if you create a scheduler instance on thread A and pass it to thread B, if B calls schedule then the callback will be run on B.

Perhaps this behavior is not intuitive? In that case it should be either documented more thoroughly or reconsidered — I can imagine semantics where the creating thread is always used to run callbacks, for instance.

I don’t think my refactoring of this class changed these semantics, by the way, or at least it wasn’t supposed to... And it will remain true if you remove the __new__ implementation.

The latter is only to cover the common case where the same thread which creates the scheduler instance also does the scheduling: since each thread will have its own queue and trampoline, it does not make sense imho to have multiple scheduler instances per thread.

I admit I did not consider extending the class though... I suppose you’d have to override the __new__ method as well? I’ll give that some thought!

**Comment by dbrattli** [comment]
I agree that the `CurrentThreadScheduler` should handle scheduling on the **current** thread, i.e if the current thread is currently running a scheduled task, then another schedule on the same thread must be queued for later. Schedule on other threads are free to execute the task if they are not currently running executing a scheduled task. 

This is btw different from previous 1.x behaviour where we had one global `CurrentThreadScheduler` that handled scheduling for all threads and where one thread would queue if another thread were currently using the trampoline. Thus it could later be executed by a different thread than the one that queued.

**Comment by erikkemperman** [comment]
@dbrattli I just looked at the 1.x branch, the code for the CurrentThreadScheduler seems pretty much the same as just before my recent changes...

So I’m curious if I understand things properly: it seems to me that even in the old version, the callback could never be executed by a different thread, because each thread has its own queue (and therefore its own independent `schedule_required` status)?

**Comment by dbrattli** [comment]
Yes, you are right. Sorry about that. The old scheduler also had a queue per thread.

**Comment by erikkemperman** [comment]
Ah, glad to have that confirmed, thanks. I was worried I had inadvertently changed the behavior!

**Comment by jcafhe** [comment]
I believe that the 'magic' behind `threading.Local` can be a bit confusing at first (at least for me) since the sheduled items are held in a queue stored in a `Local` object.

Documentation of the [`_threading_local`](https://github.com/python/cpython/blob/master/Lib/_threading_local.py) module was very helpful for me as well as an [answer](https://stackoverflow.com/a/13240093) on StackOverflow:

>One important thing that is easily overlooked: a threading.local() object only needs to be created once, not once per thread nor once per function call. The global or class level are ideal locations.
Here is why: threading.local() actually creates a new instance each time it is called (just like any factory or class call would), so calling threading.local() multiple times constantly overwrites the original object, which in all likelihood is not what one wants. When any thread accesses an existing threadLocal variable (or whatever it is called), it gets its own private view of that variable.

**Comment by MichaelSchneeberger** [comment]
> The latter is only to cover the common case where the same thread which creates the scheduler instance also does the scheduling: since each thread will have its own queue and trampoline, it does not make sense imho to have multiple scheduler instances per thread.

Ok, I understand. But don't you sometimes need to run a trampoline inside a trampoline? The outer trampoline would start the inner trampoline, and schedule the next `ScheduledItem` not before the inner trampoline stops running.

Let's say you want to calculate the factorial of a series of numbers. With RxPY v1.6 I was able to initialize a new CurrentThreadScheduler that would do the factorials one after the other. The following code ...

``` python
#rxpy v1.6
def to_factorial(num: int, _):
    scheduler = CurrentThreadScheduler()        # makes sure that factorial calculation is done immediately
                                                #   on a local trampoline
    return Observable.range(1, num, scheduler).reduce(lambda acc, v: acc*v, 1)


Observable.from_([5, 2]).flat_map(to_factorial).subscribe(print)
```
... would produce an observable that first emits 5!=120 and then 2!=2.

In the current RxPY version, the equivalent code ...

``` python
#rxpy v3.0
def to_factorial(num: int):
    scheduler = CurrentThreadScheduler()
    return rx.range(1, num + 1, scheduler=scheduler).pipe(op.reduce(lambda acc, v: acc * v, 1))


rx.from_([5, 2]).pipe(op.flat_map(to_factorial)).subscribe(print)
```

... would produce an observable that first emits 2 and then 120.

**Comment by jcafhe** [comment]
Not sure if it solves your problem, but a workaround if you want to get rid of concurrency, i.e. blocking the outer observable until the inner finishes, I assume you can use the `run()` method:
```python
import rx
from rx import operators as ops

def to_factoriel(num: int):
    return rx.range(1, num + 1).pipe(
        ops.reduce(lambda acc, v: acc * v, 1),
        ).run()

rx.from_iterable([5, 2]).pipe(ops.map(to_factoriel)).subscribe(print)
```

Alternatively, if order maters,  you can emulate a `concat_map` like before with the `merge` operator and max_concurrent = 1.
```python
import rx
from rx import operators as ops

def to_factoriel(num: int):
    return rx.range(1, num + 1).pipe(
        ops.reduce(lambda acc, v: acc * v, 1),
        )

rx.from_iterable([5, 2]).pipe(
    ops.map(to_factoriel),
    ops.merge(max_concurrent=1),
    ).subscribe(print)
```

**Comment by erikkemperman** [comment]
@MichaelSchneeberger Thanks for the example — I did not intend for the behavior to change, but looks like it did... I’ll look into it, but it’ll be a couple of days before I have some time.

**Comment by erikkemperman** [comment]
@MichaelSchneeberger Actually, I just tried your example quickly on the current master branch. I get `120` first and then `2`. I've run it a bunch of times, in case there might somehow be some non-deterministic factor, but no.

fact.py:
```python3
import rx
from rx.concurrency import CurrentThreadScheduler
import rx.operators as op

if __name__ == '__main__':
    def to_factorial(num: int):
        scheduler = CurrentThreadScheduler()
        return rx.range(1, num + 1, scheduler=scheduler).pipe(
            op.reduce(lambda acc, v: acc * v, 1))

    rx.from_([5, 2]).pipe(op.flat_map(to_factorial)).subscribe(print)

```

result:
```bash
>> git checkout master
Switched to branch 'master'
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
(venv) erik  ~/Workspace/RxPY 
>> python fact.py 
120
2
```

**Comment by jcafhe** [comment]
PR #360 appears to solve it by chance, right on time :tada: :

**Comment by erikkemperman** [comment]
Well, I am running this before pulling in that change...

**Comment by MichaelSchneeberger** [comment]
@erikkemperman yes, you are right. I had an older version of RxPY. Sorry.

I think the reason why the factorial example actually works with RxPY v3.0 (as you demonstrated) is because the priority queue gets deleted every time `CurrentThreadScheduler` is called. If I run ...

```python
print(current_thread_scheduler._local.queue)
CurrentThreadScheduler()
print(current_thread_scheduler._local.queue)
```

... I get two distinct priority queue objects ...

```
<rx.internal.priorityqueue.PriorityQueue object at 0x7f20532c82b0>
<rx.internal.priorityqueue.PriorityQueue object at 0x7f2053bf9588>
```

**Comment by MichaelSchneeberger** [comment]
@jcafhe yes, that way you avoid an inner trampoline. I agree. However, I believe sometimes it is useful to have the possibility of running an inner trampoline.

**Comment by erikkemperman** [comment]
@MichaelSchneeberger Well that seems incorrect, maybe the threading.local constructor is in the wrong place?

**Comment by MichaelSchneeberger** [comment]
you probably want to have everything in the `__init__` method?

``` python
    def __init__(self) -> None:
        """Creates a scheduler that schedules work as soon as possible
        on the current thread."""

        thread = threading.current_thread()
        local: 'CurrentThreadScheduler._Local' = CurrentThreadScheduler._global.get(thread)
        if not local:
            local = CurrentThreadScheduler._Local()
            CurrentThreadScheduler._global[thread] = local

        self._local = local
```

Because ...

``` python
class A:
    obj = None

    def __new__(cls, *args, **kwargs):
        if A.obj is None:
            A.obj = super().__new__(cls)

        return A.obj

    def __init__(self):
        print('init A')

A()
A()
```

... will print "init A" twice.

If you do that, then the factorial example prints 2 and then 120.

**Comment by erikkemperman** [comment]
No, I don’t believe so — then we’d not enforce the one-scheduler-per-thread policy. I think it should probably be a static property.

**Comment by erikkemperman** [comment]
OK, I think I have this figured out.

First, the local constructor is indeed in the wrong place, it should not be re-created with each scheduler instance. I have submitted [this PR](https://github.com/ReactiveX/RxPY/pull/363) to address that problem.

Second, you are absolutely correct: before I introduced the `__new__` implementation which enforces a single scheduler instance per thread, you could have several of them, each with their own queue. 

That way, because of the semantics of this scheduler, the callbacks would never overtake one another, the current thread would not get around to handling the second part until the queue for the first part is empty and the thread is not occupied.

With the `__new__` method you will have a single queue,  the steps to compute both factorials  are all done on the same queue and the order in which we see the output printed is simply due to `2` being smaller than `5`.

(This does not apply internally, because the singleton instance `current_thread_scheduler` is used, and there will be a single queue per thread because there is a single scheduler instance.)

So I guess the question is, is this scenario a sufficient reason for allowing several CurrentThreadScheduler instances per single thread? If it is, we should get rid of the `__new__` method. But then we'd have to remain careful about using the singleton instance internally -- I was hoping to remove the singletons altogether, but perhaps that's the wrong approach.

Alternatively, we keep the `__new__` method and the enforced policy of a single scheduler instance per thread. But then, for scenarios like these, if the order of things is important you would have to ensure that yourself.

I'm not sure either way... But it's definitely true that my patch has this subtle change in behaviour relative to 1.x, so if we keep it it ought to be documented.

If we get rid of the method, then inheritance will work as expected. But otherwise, I think I have found a way to make that work as well, just needs a bit more testing before I would submit that. We'll need a decision on keeping/discarding `__new__` first.

Thoughts?

**Comment by MichaelSchneeberger** [comment]
> First, the local constructor is indeed in the wrong place, it should not be re-created with each scheduler instance. I have submitted this PR to address that problem.

Yes, `_local = _Local()` defined as a static variable in the `CurrentThreadScheduler` seems to do the job.

> But then we'd have to remain careful about using the singleton instance internally -- I was hoping to remove the singletons altogether, but perhaps that's the wrong approach.

Could you explain why you want to get rid of singleton instances? Are you talking about `current_thread_scheduler`? Couldn't we get rid of `current_thread_scheduler`, by creating a `CurrentThreadScheduler()` once when the `Observable.subscribe` method is called? Well, this would then require the `scheduler` argument of the `def _subscribe_core(self, observer: typing.Observer, scheduler: typing.Scheduler = None)` method to not be optional anymore.

**Comment by MichaelSchneeberger** [comment]
Here is another thing. If I schedule two actions I expect them to be executed in order. With the new implementation of `CurrentThreadScheduler` that would not be necessarly true anymore.

Let's say you call the following two functions on two different threads, first `to_be_called_on_thread1` and then `to_be_called_on_thread2`.

```python
def to_be_called_on_thread1():
    current_thread_scheduler.schedule(action1)

def to_be_called_on_thread2():
    current_thread_scheduler.schedule(action2)
```

Depending on how full the `PriorityQueue` on each of these threads is, it might be that action 2 is called before action1.

**Comment by erikkemperman** [comment]
Well, the introduction of these singletons was before I ever got involved with rxpy — but my impression is they were introduced because of problems with having several instances in the same pipeline.

And it seems to me that, if this is apparently a “dangerous” thing to do, it ought to be enforced not just internally but for end-users as well. Hence the `__new__` method. And if that works as intended, there’s no longer a need for things like `current_thread_scheduler` and it can be removed. Also, they’re not pretty :-)

But I’m a newbie here... Perhaps others can correct me if I’m wrong about this.

About the order of execution: I don’t think it’s reasonable to expect different threads (and thus different schedulers, effectively) to maintain this order.

But I agree that, as things are now, it might not be sufficiently clear that you get effectively distinct schedulers in different threads, even if you appear to be using a single scheduler instance. But that’s a documentation issue, imho.

**Comment by jcafhe** [comment]
> So I guess the question is, is this scenario a sufficient reason for allowing several CurrentThreadScheduler instances per single thread?

If so, that should be explicit, something like a `clone` method. Do you know if it's even possible to have multiple `_Local` objects per thread? Or maybe by using a class factory to dynamically create a Local class per scheduler instance.

> About the order of execution: I don’t think it’s reasonable to expect different threads (and thus different schedulers, effectively) to maintain this order.

I agree with @erikkemperman. That would require some kind of synchronization that is out of scope of rx IMO. I believe the rx contract guaranties the order of different items within a single observable, not between multiple ones (even between an inner/outer observables ?).

**Comment by erikkemperman** [comment]
> Do you know if it's even possible to have multiple _Local objects per thread? Or maybe by using a class factory to dynamically create a Local class per scheduler instance.

You’re right, that should not work. Even if you have distinct scheduler instances for the same thread, they should still get the same queue.

The only reason it _seems_ to work currently is that I messed up the local constructor :-)

**Comment by MichaelSchneeberger** [comment]
> About the order of execution: I don’t think it’s reasonable to expect different threads (and thus different schedulers, effectively) to maintain this order.`

At least, the previous `CurrentThreadScheduler` implementation did maintain the order.

Another solution is to add a new scheduler like `TrampolineScheduler` (see [Monix](https://github.com/monix/monix/blob/master/monix-execution/shared/src/main/scala/monix/execution/schedulers/TrampolineScheduler.scala)) that implements the previous version of `CurrentThreadScheduler`.

**Comment by MichaelSchneeberger** [comment]
Ups, I'm wrong. I didn't realize that the previous implementation of `CurrentThreadScheduler` created a new queue for each thread as well. Forget my comment about maintaining the order.

```python
    def get_queue(self):
        ident = threading.current_thread().ident

        with self.lock:
            return self.queues.get(ident)

    def set_queue(self, queue):
        ident = threading.current_thread().ident

        with self.lock:
            self.queues[ident] = queue

    queue = property(get_queue, set_queue)
```

**Comment by MichaelSchneeberger** [comment]
To be continued in #383
