### ISSUE TITLE
what is the function of the  `on_error` function in subscribe ?

### ISSUE THREAD

**Issue by honglei** [ReactiveX/RxPY#380]
Version: python3.7/Rxpy3.0.0b1
The on_error won't catch the Exception raised in function `next_proc`, so , what is the function of `on_error`?

```python
from rx import of
source = of(None, 444, "Gamma", "Delta", "Epsilon")
def next_proc(i):
    print(f"Len: {len(i)}")
source.subscribe(
    on_next = next_proc ,
    on_error = lambda e: print(f"Error Occurred: {e}"),
    on_completed = lambda: print("Done!"),
)
```

**Comment by dbrattli** [comment]
Hi, I believe this is a bug, so thanks for reporting.

### For the maintainers: 
The `on_error` handler should have been called. It might be because of some refactoring we did with `AutoDetachObserver` and `ObserverBase` for v3. 

From AutoDetachObserver.py
```py
def on_next(self, value: Any) -> None:
        if self.is_stopped:
            return

        try:
            self._on_next(value)
        except Exception:
            self.dispose()
            raise
```

The problem is that the we dispose before raising so we are muted (`self.is_stopped`) when the exception goes down the chain.  I feel it's best to just let the exception bubble to the top (`Observable.of`) and then mute when the error goes down the chain again, thus removing the `try/except/dispose` in `on_next()`

**Comment by jcafhe** [comment]
@dbrattli  Ok, that should solve the issue. Just out of curiosity, I've been digging a little bit in `subscribe` & `AutoDetachOberver` machinery, and I thought that the chain links was directly inter-connected, but in fact `AutoDetachObserver` is **always** used to 'wrap' operators, is that correct? 
Also what differs from the current case is that an operator is responsible for calling his observer `on_error` if an Exception is raised during whatever work it has to do.

**Comment by dbrattli** [comment]
Yes, inside the operator chain (going up) is the observer chain (going down). The observer chain gets an autodetach-observer stitched in between each observer in the chain. This is because we do not trust the source e.g `rx.create` or up-stream operator, and we do not trust the sink e.g the down-stream observer which might be from a custom made operator or the the final subscribed obsever in the chain.

This is the traditional Rx way, but by letting the exception bubble up we then need to trust the source to do the right thing, and it might not do that if it's a custom source (`rx.create´) or operator. But there are limits on how much defensive programming you should do in a framework (imo).
