### ISSUE TITLE
using with async functions

### ISSUE THREAD

**Issue by siemib** [ReactiveX/RxPY#415]
Hello,

I am trying to use ```pipe()``` operator with ```ops.map``` which is an async function. Unfortunately that does not work.

I am seeing the following error:
```AttributeError: 'coroutine' object has no attribute 'subscribe_'```

Would be the correct way to use Observables with async functions?

Thanks

**Comment by dbrattli** [comment]
The current RxPY does not handle Async Observables. But you can still compose the coroutine into the pipeline using `ops.flat_map` where you can return a `Future` in the mapper (instead of an `Observable`). Thus use `asyncio.create_task(coro())` or `asyncio.ensure_future(coro())` to make your coroutine return a `Future`.

**Comment by belolap** [comment]
Operator `flat_map()` not working with `Future` for me now because of #457

**Comment by dbrattli** [comment]
FYI: aioreactive is back: https://github.com/dbrattli/aioreactive
