### ISSUE TITLE
Expand seems to be hitting some limit.

### ISSUE THREAD

**Issue by c200chromebook** [ReactiveX/RxPY#482]
I have created this simple pipeline which should count up to 500, however, it only counts up to 319. 319 is somewhat less than 500, therefore I am confused. Why is this happening?

Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] on win32
rx.__version__
'3.0.1'
```python
import rx
from rx import operators as ops

work = [0]
z = []
init = rx.from_list(work).pipe(ops.expand(lambda x: rx.Observable() if x == 500 else rx.from_list([x+1])))
init.subscribe(lambda x: z.append(x))
print(max(z))
```

**Comment by jcafhe** [comment]
Hi,

You have reached the maximum recursion depth. This error is hidden because you didn't specify an error handler in the subscribe method. Try this:
```python
init.subscribe(lambda x: z.append(x), on_error=print)
```
To avoid strict recursive calls, you can use a "trampolined" scheduler which mimics recursion, like `CurrentThreadScheduler`, `NewThreadScheduler`, `ThreadPoolScheduler`, etc.

```python
import rx
from rx import operators as ops
from rx.scheduler import CurrentThreadScheduler

scheduler = CurrentThreadScheduler()
work = [0]
z = []


def mapper(x):
    if x == 500:
        return rx.empty()
    else:
        return rx.just(x + 1)

init = rx.from_list(work).pipe(
    ops.expand(mapper)
    )

init.subscribe(
    lambda x: z.append(x),
    on_error=lambda e: print(f'error: {e}'),
    on_completed=lambda: print(f'completed'),
    scheduler=scheduler)

print(max(z))
```
