### ISSUE TITLE
Schedulers behaviour question.

### ISSUE THREAD

**Issue by ldulcic** [ReactiveX/RxPY#490]
Hi! I'm fairly new to RxPY (I worked with RxJava before) and so far it's been a good experience but there are some examples that I just don't understand well enough. Here is an example where I'm not sure what's going on.

Observable:
```python
def observable():
    def subscribe(observer, scheduler):
        while True:
            observer.on_next("item")

    return rx.create(subscribe)
```

When I subscribe to observable and sample it every second, `on_next` is never called:
```python
observable().pipe(
    ops.sample(1)
).subscribe(on_next=print)
```
If I omit `sample` operator, everything works fine. 

When I subscribe observable on background thread, everything works fine, `on_next` is called every second:
```python
observable().pipe(
    ops.subscribe_on(ThreadPoolScheduler(1)),
    ops.sample(1)
).subscribe(on_next=print)
```
```
item
item
item
...
```
Also, if I subscribe on background thread via `scheduler` parameter it doesn't work, `on_next` is never called:
```python
observable().pipe(
    ops.sample(1)
).subscribe(on_next=print, scheduler=ThreadPoolScheduler(1))
```

I'd appreciate if someone could explain why is `on_next` never called in first example, I also don't understand what's the difference between second and third example? I tried googling, reading the docs and searching issues but I didn't find anything that clarifies this.

Also is there some way to get back on main thread with `observe_on` when we subscribe on background thread? I didn't found `MainThreadScheduler`.

I'm using Python 3.6 and rx==3.0.1.

**Comment by MainRo** [comment]
The sample operator subscribes to 2 observables: its source, and a timer created internally.

In the first example no scheduler is provided, so the whole subscription is done on the current thread. When sample subscribes to the source observable, this call never returns due to the infinite loop in observable::subscribe. So the sample operator cannot subscribe to the timer observable. As a consequence "observable" infinitely sends items that are never forwarded by the sample operator.

In the second example the subscription to "observable" is done on a dedicated thread. In this case both "observable" and the timer observable can run concurrently: The subscription to "observable" is done in the threadpool thread, so the sample operator is not blocked and can subscribe to the timer observable. 3 threads are used here: One for "observable" (the threadpool), one for the timer (the TimeoutScheduler), and the main thread of the program.

In the third example, a default scheduler is provided. The situation is similar to the first example: The whole pipeline is subscribed from the threadpool thread while in example 1 it was from the main thread of the program. The same thing happens here: sample can never subscribe to the timer observable because the subscription to "observable" never returns.

Hope this clarifies the different behaviors.

**Comment by ldulcic** [comment]
Thank You for explanation @MainRo!
