### ISSUE TITLE
Clarify incompatibility of v1 branch with python 3

### ISSUE THREAD

**Issue by mnieber** [ReactiveX/RxPY#534]
I'm interested in using RxPY for my project that has to support python 2 and 3. Looking at the documentation of the v1 branch (https://github.com/ReactiveX/RxPY/tree/release/v1.6.x) it appears that this branch does not work for python 3 versions greater than 3.4. Still, I wonder if that's confirmed to be true or whether at the time it simply wasn't tested.

It would be great if the v1 documentation could be updated with this information (i.e. make it explicit what - if any - the support is for python 3.5 and higher)

**Comment by MainRo** [comment]
v1 works well on 3.6, and I think that I also used it on 3.7. So yes, we should update the doc, and test with more recent versions.

**Comment by garysb** [comment]
Hi @MainRo , thanks for the clarification. I am also producing an extension that needs to work across multiple versions of Python Maya Python 2.7 and Blender Python 3.7 amongst others.

Is there any plan to get the latest RxPY to be compatible with Python 2.7 ever? It would be a shame to be stuck using an antiquated version due to the constraint on Python 2.7?

**Comment by MainRo** [comment]
RxPY v3 uses some syntax available only on python 3. We chose to move forward with this major release. I understand that it prevents some projects to migrate due to dependencies, but with python 2 now being dead migration to python 3 should accelerate.
