### ISSUE TITLE
Generate the whole event flow diagram

### ISSUE THREAD

**Issue by wyujie** [ReactiveX/RxPY#576]
Hi RxPY team, is there an easy way to generate the whole event flow diagram after defining all functions in code ?

**Comment by MainRo** [comment]
Do you mean a way to dump/log all events going through the graph, or generating a diagram of the operators graph?

For the first case, you can add probing points at specific locations in the graph. You can do this with the "do_action" operator.

For the second case, unfortunately, this is not possible today. This is something I've been thinking since some time. Up to now, the only solutions I found involve heavy changes to the current code-base. My preferred way to deal with this would be that the RxPY API generates an AST instead of instantiating the operators directly. Then we could materialize this AST to the current RxPY operators, or generate a diagram of the graph. This would also allow interesting things like transferring the AST to a remote system, instantiating it with an alternative implementation, compiling it to native code...

**Comment by wyujie** [comment]
Hi MainRo, my question is for the second case. Thanks your kind answer.
