### ISSUE TITLE
Is this the expected behavior of the `window_with_count`-operator?

### ISSUE THREAD

**Issue by steuke** [ReactiveX/RxPY#590]
I have been trying to wrap my head around the  `window_with_count`-operator, but it just does not do what I would expect from looking at the [ marble-diagram in the documentation](https://rxpy.readthedocs.io/en/latest/reference_operators.html#rx.operators.window_with_count). Here is an example with expected and actual output:

### Minimal example

```
from rx import operators, from_


def sliding_window_example(window_size: int):
    values = range(99, 103)
    source = from_(values).pipe(
        operators.window_with_count(count=window_size, skip=1),
        operators.do_action(on_next=lambda x: print(f"New window")),
    )
    print("Subscribing to source")
    source.subscribe(lambda the_window: the_window.subscribe(print))


if __name__ == "__main__":
    sliding_window_example(window_size=3)

```

### Expected output

I would expect each window to emit the values as they appeared in the source observable:

```
Subscribing to source
New window
99
New window
99
100
New window
99
100
101
New window
100
101
102
New window
```

### Actual output

But instead, each window seems to emit the most recent value repeatedly:

```
Subscribing to source
New window
99
New window
100
100
New window
101
101
101
New window
102
102
102
New window
```

## Questions

1. Am I doing something wrong, or is this the expected behavior?
2. Is there a way to achieve my expected output from the input values using the window-operator in some other way?

Thanks for taking the time! Best,
Stefan

**Comment by MainRo** [comment]
The result that you see is the expected one: On the example in the documentation, the two windows emit their items sequentially because skip is None, i.e count, i.e. 3.
In your case, you set count to 3 and skip to 1. So you set a stride of 1. As a consequence, a new window is created each time an item is received.
The fact that you see all same values emitted is due to the event based nature of rxpy: Several windows are "alive" at the same time, but they emit items as they receive items on their source. They do NOT buffer all items to emit them sequentially.
So your code corresponds to this marble diagram:

```
-99---100---101---102-------|
[  window_with_count(3, 1)  ]
-+----+-----+-----+---------|
                  +102------|
            +101--102-------|
      +100--101---102-------|
 +99--100---101---102-------|
```

**Comment by steuke** [comment]
Thank you so much for the explanation, this was really helpful. I did assume the window-operators are like the buffer-operator, except that they return an observable. I see now that was a big misunderstanding on my part.

Again, thanks for the help, I really appreciate it!
