### ISSUE TITLE
RxPY v4 code name ReactiveX

### ISSUE THREAD

**Issue by dbrattli** [ReactiveX/RxPY#601]
This issue discusses and tracks RxPY v4:

- [x] Rename package to `reactivex` on PyPI so we can see dependencies etc. since `rx` is taken by the old MS repo
- [x] Generic type annotations https://github.com/ReactiveX/RxPY/pull/597#
- [x] Format code using [Black](https://github.com/psf/black) at default settings
- [x] Sorting of imports using [isort](https://github.com/PyCQA/isort)
- [x] Type checking using mypy (except operators)
- [x] Type checking using pyright (basic)
- [x] Type checking using pyright (strict)
- [x] Use pyproject.toml instead of setup.py ([PEP-518](https://www.python.org/dev/peps/pep-0518/))
- [x] Use [Poetry](https://python-poetry.org/) to build and test
- [x] Use pre-commit to enforce code style before commit (formatting, isort, mypy, ...)
- [x] ~~Use [Versioneer](https://github.com/python-versioneer/python-versioneer) for version handling and CI integration~~ (wait until it supports pyproject.toml)
- [x] Add publish action for releases and use dynamic versioning based on git tags
- [x] Fix pipe operator (it should be called compose). Add a proper pipe operator. https://github.com/ReactiveX/RxPY/pull/605/files
- [x] Move v3 aside as separate release branch `release/v3.2.x`
- [x] ~~Deprecation of `from_callback`~~ 
- [x] ~~Deprecation of `TkinterScheduler`~~
- [x] ~~Deprecation of `PyGameScheduler`~~ 
- [x] ~~Deprecation of `WxScheduler`~~
- [x] ~~Deprecation of `EventletScheduler`~~

Evolutions to be discussed:
- [ ] Add optional arguments to subscribe
- [ ] make backtrace more readable: when an error occurs, provide the backtrace of the operator creation instead of the one of event flow. This would make tracing an exception much more easy.

**Comment by dbrattli** [comment]
By deprecation I think we should perhaps move the code to the `examples` folder so that people use them as starting point for similar code, but the code is un-supported. As for `TkInterScheduler` I'm unsure since I use that scheduler a bit myself and the `timeflies_tkinter.py` demo is pretty awesome and works without having to install any extra framework. But tkinter is probably being removed from Python (not bundled with anymore).

**Comment by dbrattli** [comment]
As for enforcing code style it's quite common to use [pre-commit](https://pre-commit.com/) these days so that you cannot produce non-valid commits (thus avoiding "formatted using black" commits etc). But some feel it's a bit intrusive to add git-hooks in the repo. What are your feelings about this?

**Comment by MainRo** [comment]
I would be cautious on pre-commit hooks: I find them nice to avoid obvious issues, but annoying when being too sensible.
For example, on code style sometimes you want to explicitly break it to favor readability (more specifically, I regularly use lines with a little bit more than 80 chars).

**Comment by MainRo** [comment]
I would also be interested in pushing additional asyncio operators. This could be done independently of a v4 since it would only be additions. However since I did not take the time for a proposal for many months, that may be the occasion.
I already use custom operators for:

- converting an async iterator to an observable
- converting an observable to an async iterator

Also, I will probably need a "do_await" operator soon.
We could provide operators for these, with a "reasonable" backpressure strategy for those that need it.

**Comment by dbrattli** [comment]
As for the pre-commit hooks, they will only enforce the rules of the repository. So they will not add additional rules. If they break, then the CI will also break. The difference is that you discover it earlier. Both black and isort are uncompromising which is good since it makes you focus on what matters. Black defaults to 88 chars which is a bit more than 80.  

Additional operators are great and don't will just require a minor version change. As for async iterators you probably want to convert an async iterable to an observable since an iterator is the dual of an observer (both are hot). 

As for additional parameters to subscribe we might want to consider what Reaqtor does. This enables stateful operators, i.e save/restore internal state ref: https://github.com/reaqtive/reaqtor/blob/438ab62b8f5b2cb726291d5ffa21b139e0d203a1/Reaqtive/Core/Reaqtive.Linq/Reaqtive/Operators/Scan.cs

**Comment by MainRo** [comment]
I will have a deeper look at the reaqtor design. I do similar things in rxsci, and I am currently experimenting with alternative/simpler solutions.

**Comment by dbrattli** [comment]
I used to work with that code base when at MS so I know it really well. Great to see it's been open sources. It btw inspired the scheduler in the subscribe call (that no other Rx impl had). Stateful Rx (i.e persistable state) would be great to have in Python, so we should consider something similar (but simpler imo)

**Comment by MainRo** [comment]
Some more thoughts on additional subscribe arguments and persistable states: 

If I am correct, on reaqtor each stateful operator still manages its own state, and exposes it via load/save methods. I agree that the whole reaqtor design may be too complex for RxPY (where we probably have a broader audience in use cases). On the other way, there are probably many applications that would benefit from using an external state store. Maybe a balance in flexibility and complexity would be to provide a state-store object during subscription as we do for the schedulers. The stateful operators would use the store APIs to set and get their states. This should be simple to implement and expose. I also see another advantage here: Since each operator would not manage its state location directly, it becomes possible to use disk-based stores. This is common in applications where the state can be very big. KV stores like rocksdb with a memory cache are often used for that. 

On that part, we could provide a default in-memory state-store. Then, anybody could replace it with their own implementation. It would be simple and very flexible.

Going further on that and the possibility to add additional arguments to subscribe, this state-store, as well as the scheduler, could be provided as part of a generic mechanism: Subscription could take a kwargs as input, where we reserve some keys and allow any custom key: scheduler and state-store would be reserve keywords, and we would let the users specify other ones. One use-case for this is the possibility to configure some operators at subscription time instead of creation time. This is something that would be very valuable when composing operators as generic/reusable components.

**Comment by MainRo** [comment]
There is another topic that may or may not be relevant in a v4: Support of infrastructure for backpressure libraries. 

For now, people that need some support of backpressure have to reimplement a whole reactive library. This is typically the case of [rxbackpressure](https://github.com/MichaelSchneeberger/rxbackpressure). This is unfortunate since many (most?) operators should be reusable (filter, map, count...). 

I experimented with [callbags](https://github.com/callbag/callbag) on python recently and it may be an inspiration to get rxpy "backpressure ready". Basically, it is a construct where the flow is bi-directional. The original intent was to unify the implementation of push and pull systems. But we could use the upstream flow for control flow messages (in addition to subscriptions).

I did not look at what it would mean to use this as a backend for rxpy. I like the idea that backpressure is handled by dedicated libraries (because the topic is so broad), but rxpy should allow writing such libraries as an enhancement, not a side library with adapters to/from rxpy.

**Comment by dbrattli** [comment]
The problem with kwargs is that they cannot be typed. It will have to be `**kwargs: Any`. Thus it's impossible to know if your code is correct or not. It's better to use a Protocol of some sort so we can have static duck typing.

But before we do any of this, I would like to make a new release with the current changes since it's nearly 100% compatible with v3, and the code quality have been improved massively (imo).

**Comment by MainRo** [comment]
> The problem with kwargs is that they cannot be typed.

Yes, that was what I feared. With dynamic-dispatch, we could define a base type to provide the scheduler and a state-store. Then custom additions would still be possible by extending this type.

> But before we do any of this, I would like to make a new release with the current changes

Sure.

**Comment by dbrattli** [comment]
Version v4.0.0 has been released 🎉  Let's move the discussion of v5 to the discussions area.
