### ISSUE TITLE
ProcessPoolScheduler

### ISSUE THREAD

**Issue by ChromoX** [ReactiveX/RxPY#70]
Hello,

I am currently using Reactive Programming paradigm as an alternative to the Actor model. I was expecting that it would be easy to dictate processing in multiple processes by simply using the correct scheduler. After looking I can't find any scheduler that seems to use multiple processes. I was thinking about building a ProcessPoolScheduler, but I was wondering what problems you guys see with implementing something like that?

I understand that the Reactive contract is such that streams are processed in order, but I know many applications don't require that assumption.

Also if something like the ProcessPoolScheduler is not possible, how might one go about trying to build a parallel processing system in Python where you have the GIL to contend with.

Thanks,
Jeffrey

**Comment by dbrattli** [comment]
This is a very interesting topic. There have been some previous discussions in #65 and #67 that you should look at. Some initial thoughts: There is nothing in the Rx contract that prevents you from processing items in parallel, as long as ordering is maintained (think overlapping processing). If ordering is not relevant for your application then you should use the initial sequence to just schedule work, and have that create new streams of processed work that you can flatten to a result stream (see #67 for an example).

You also need to check if the work you want to do in parallel is IO or CPU bound and if the processing is done by extensions libraries or by Python code. If the work you want to do is IO bound, you should probably use `AsyncIOScheduler` to achieve concurrency. If work is CPU bound but done in extension libraries like NumPy, then use the `ThreadPoolScheduler`. Work will be done in parallel since extension libraries like NumPY are not affected by the GIL. If work is CPU bound, and work needs to be done by Python code, then the GIL is a problem and you may want to write a `ProcessPoolScheduler`. If a `ProcessPoolScheduler` is the right answer or not depends on how long-running your CPU bound work will be.

But I can't see any problems with building a `ProcessPoolScheduler` so it would be awesome if you want to try. Then the next step could be to make an `RemotingScheduler` to schedule work on other nodes.

**Comment by ChromoX** [comment]
Thanks for the response. I've been trying to wrap my head around how invoke/disposables work in schedulers. Regardless I assume that the RxPy project doesn't have a ThreadPoolScheduler? I couldn't find one in the rx.concurrency folder.

**Comment by dbrattli** [comment]
No we don't have a `ThreadPoolScheduler` yet either, so there are many possible projects for those who want to contribute.

**Comment by tadas-subonis** [comment]
Did anybody do any work on this?

**Comment by MainRo** [comment]
For information I published a [ray](https://ray.io) operator here:
https://github.com/maki-nage/rxray

It can be used for multi-processing purpose, but also to distribute a RxPy pipeline on a cluster of machines.

**Comment by dbrattli** [comment]
Closing this for now
