### ISSUE TITLE
Why does TwistedScheduler raise AlreadyCalled error?

### ISSUE THREAD

**Issue by mchen402** [ReactiveX/RxPY#78]
**Minimal working example**: [see SO post](http://stackoverflow.com/questions/35582192/why-does-twistedscheduler-raise-alreadycalled-error)

The issue documented in the post above seems to be due to the following in `rx.concurrency.mainloopscheduler.TwistedScheduler`:

	def dispose():
		handle[0].cancel()

I believe the problem is that `handle[0]` (a `delayedCall`) might already have been called prior to cancellation. So should we wrap the above with a `try`?

	def dispose():
		try:
			handle[0].cancel()
		except AlreadyCalled:
			pass

**Comment by jcwilson** [comment]
I have run into the same underlying error when simply using the `debounce()` operator. I've tested your fix locally and it seems to allow things to work normally. It seems a little strange to be watching for this exception as "expected behavior".

An alternative could look something like this:
```
def schedule_relative(self, duetime, action, state=None):
	# ...
    def complete(result):
        handle[0] = None
        return result

    log.debug("timeout: %s", seconds)
    handle = [deferLater(self.reactor, seconds, interval).addBoth(complete)]

    def dispose():
        if handle[0] is not None:
            handle[0].cancel()
            
    return CompositeDisposable(disposable, Disposable(dispose))
```
but it's basically just a more verbose expression of your solution.

Hope this can get resolved soon, because as it is, the `TwistedScheduler` is unusable.

**Comment by dbrattli** [comment]
I like the alternative version. Should we set `handle[0]` to None after `.cancel()`, or will `cancel()` `complete()` it?

**Comment by jcwilson** [comment]
Yep, you're correct. `cancel()` will invoke `complete()`.

If going with this solution, we should amend `complete()` as follows, since we don't want to propagate `Failure` results and nothing really cares about the result here anyway. (calling `cancel()` generates a `Failure`):
```
def complete(result):
        handle[0] = None
```

A more concise form would be:
```
# ...
log.debug("timeout: %s", seconds)
# The array form of `handle[0]` isn't necessary here
handle = deferLater(self.reactor, seconds, interval).addErrback(lambda _: None)

def dispose():
    if not handle.called:
        handle.cancel()

return CompositeDisposable(disposable, Disposable(dispose))
```
All we're really doing is replicating work that's done in `Deferred.cancel()` to prevent it from raising the `AlreadyCalled` exception. So functionally, this is equivalent to @mchen402's solution, just more explicit about what's happening. See my comment on https://github.com/mchen402/RxPY/commit/1d8ff14d1d0b286200e98f2fe23c6d5e10ab5c55 about a possible functional difference between using a `DelayedCall` from `callLater()` vs a `Deferred` from `deferLater()`

**Comment by dbrattli** [comment]
Looks good to me. What do you think @mchen402 ? Do you want to update the pull request?

**Comment by mchen402** [comment]
Sure - i'll do that now

**Comment by jcwilson** [comment]
:+1: thanks!

What's the timeline looking like for the next PyPI release?

**Comment by dbrattli** [comment]
If you can confirm that develop branch works as expected, then I can start to prepare a new release for PyPI.

**Comment by jcwilson** [comment]
I can vouch that the develop branch works for me. I cloned it, checked out `develop` and ran `python setup.py develop` before testing my app again. I also verified that it was using the github version and not the installed site-packages version.

**Comment by dbrattli** [comment]
@jcwilson PyPI should be updated now

**Comment by jcwilson** [comment]
awesome! just tried it out. seems to be working fine :) thanks @dbrattli and @mchen402
