### ISSUE TITLE
Why does AutoDetachObserver ignore my on_error handler?

### ISSUE THREAD

**Issue by mchen402** [ReactiveX/RxPY#86]
**Minimal working examples**: see [SO post](http://stackoverflow.com/questions/36463616/why-does-autodetachobserver-ignore-my-on-error-handler-in-rxpy)

The issue documented in the post above seems to be due to the following in `rx.autodetachobserver`

```
def _next(self, value):
    try:
        self.observer.on_next(value)
    except Exception:
        self.dispose()
        raise
```

**MWE1 cause**: when an `Exception` is caught, it is simply `raise`d and `self.observer.on_error()` does not get called.

**MWE2 cause**: The call to `self.dispose()` causes `self.is_stopped` to be set to `True` so when `self.on_error()` is called, the condition `if not self.is_stopped` is `False` and so prevents anything from happening.

So should it not just be:

```
def _next(self, value):
    self.observer.on_next(value)
```

because you don't need to catch errors in `_next`. This is because the caller uses catches exceptions -- I'm thinking about use cases like:

```
def subscribe(observer) # observer is AutoDetachObserver
    try:
        observer.on_next(3)
    except Exception as e:
        observer.on_error(e)
```

**Comment by dbrattli** [comment]
Rx operators do not catch exceptions that occur in a call to OnNext, OnError, or OnCompleted.  This is because we expect that (1) the observer implementor knows best how to handle those exceptions and we can't do anything reasonable with them and (2) if an exception occurs then we want that to bubble out and not be handled by Rx.

Read more at:
https://social.msdn.microsoft.com/Forums/en-US/ee5dba5d-eea9-4d85-8f58-c2e1c71ef33a/about-the-contracts-in-rx-exceptions-and-blocking?forum=rx

**Comment by mchen402** [comment]
OK, while I understand the error-handling semantics, I don't yet agree with them. Why not do:

- if there is an error in `on_next()`, then call `on_error()`
- if there is an error in `on_error()` then `raise` and bubble up

To address your points individually:

1. *the observer implementor knows best how to handle those exceptions and we can't do anything reasonable with them*

   **yes, the observer implementor knows how best to handle exceptions precisely by implementing an `on_error()` method. So we should just call `on_error()` when `on_next()` throws**

2. *if an exception occurs then we want that to bubble out and not be handled by Rx.*

  **Given that we pass `on_next()` errors to `on_error()`, if `on_error()` then also has an exception or rethrows the error it was passed because it does not know how to handle it, we *then* can bubble up the exception.**

**Comment by dbrattli** [comment]
I see your point, but I'm not fully aware of the reason for this decision, From 6.4 of [The Rx Design Guidelines](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Documentation/Rx%20Design%20Guidelines.pdf). "Note: do not protect calls to Subscribe, Dispose, OnNext, OnError and OnCompleted methods. These calls are on the edge of the monad. Calling the OnError method from these places will lead to unexpected behavior.". So I don't want to change the semantics of this right now, but I'll check with someone who should know this better.

However, it is very easy for you to create a non-throwing observer by wrapping it in a "SafeObserver", or make a base class that catches the errors for you and forwards them to on_error() if that is what you want.

**Comment by mchen402** [comment]
OK, thanks Dag. I'll use your `SafeObserver` idea for now, but it seems like a sticking plaster:

- I have to pepper my codebase with calls to `SafeObserver` everywhere just to get what I consider should be the most intuitive and therefore default behaviour
- The base RxPY implementation does not use `SafeObserver` and so I have to deal with inconsistent behaviour between my codebase and base RxPY

I understood very little of your quote from [The Rx Design Guidelines](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Documentation/Rx%20Design%20Guidelines.pdf), so look forward to your seeking clarification from someone who knows this better.

**Comment by mchen402** [comment]
> So I don't want to change the semantics of this right now, but I'll check with someone who should know this better.

Did you manage to check with someone, Dag?
Specifically, why can't we do what was proposed earlier:

> if there is an error in on_next(), then call on_error()
    if there is an error in on_error() then raise and bubble up

**Comment by dbrattli** [comment]
Sorry didn't get any answers, but I've talked with some of the people at my team at work and they all agree that observers should not throw. They should catch exceptions themselves and propagate down (not up). This is sort of similar to iterables where we have the following:

```python
for x in xs:
    do_stuff()
```
If `do_stuff()` might throw exceptions then you want to protect that method:

```python
for x in xs:
    try:
        do_stuff()
    except Exception:
        pass # Handle exception
```
It's unusual that you want to terminate the iteration because of exceptions with `do_stuff()`, and it's also not that good to mix the exceptions from `do_stuff()` and from the `next()` call on the iterator. Throwing from the observer is equivalent to not catching the exception inside the for-loop but catching it outside:

```python
try:
    for x in xs:
        # on_next()
        do_stuff()
except Exception:
    pass # on_error()

# on_completed()
```
But your question is what to do if the developer for some reason does **not** protect `do_stuff()`, and with iterables the exception would propagate out of the for-loop which for me looks like the equivalent of sending it to `on_error()` in the case for iterables. And if the developer does not protect the for-loop then the exception would propagate up, which is equivalent to not having a try/except outside the for-loop. 

So I sort of agree with you, but I would also like some more opinions from core Rx developers. 

DB

**Comment by dbrattli** [comment]
I found some more information. This discussion from RxJava is very interesting: https://github.com/ReactiveX/RxJava/issues/3612

If we look at the difference between version 1 and version 2 of RxJava we can see that they have changed the behaviour to match your proposal. RxJava 2.0 seems to be the only Rx implementation for now that has this behaviour.

v1: https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/observers/SafeSubscriber.java
v2: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/observers/SafeObserver.java

I'm starting to get positive about making this change for RxPY as well in order to maintain the duality with Iterable for-loop above. I just have to do a few investigations to make sure we don't break anything.

**Comment by mchen402** [comment]
Thanks for looking into this, Dag.
Looking forward to seeing the change.

**Comment by dlazerka** [comment]
Also, I noticed that .map() observable method doesn't accept an Observer, which is really weird (all the examples I found online provide a lambda function). But then if I want to stream exceptions to error events, how do I call on_error() from a lambda function?

**Comment by dbrattli** [comment]
You throw an exception.

**Comment by dlazerka** [comment]
Exception gets lost and not reported anywhere (e.g. with ThreadPool scheduler).

**Comment by dbrattli** [comment]
Please open a new issue and provide a code sample.
