### ISSUE TITLE
VirtualTimeScheduler bug, and fix.

### ISSUE THREAD

**Issue by djarb** [ReactiveX/RxPY#95]
In virtualtimescheduler.py

    def get_next(self):
        """Returns the next scheduled item to be executed."""

        while len(self.queue):
            next = self.queue.peek()
            if next.is_cancelled():
                self.queue.dequeue()
            else:
                return next

        return None

should be

     def get_next(self):
        """Returns the next scheduled item to be executed."""

        while len(self.queue):
            next = self.queue.dequeue()
            if not next.is_cancelled():
                return next

        return None

As it is right now, get_next will always return the same scheduled item, resulting in an "Exception: Disposable has already been assigned" error on the second attempt to invoke it.

Alternatively, you could dequeue the item just before calling invoke, if having get_next *not* advance the state is valuable.

**Comment by dbrattli** [comment]
Thanks for pointing this out. Looking at the code I was wondering how did this ever work? Unfortunately it wasn't that easy. The patch  broke the tests since the dequeue was actually done by the run callback in `schedule_absolute`. But the code was hairy enough, so used some time to clean it up using your patch as the start. Thanks again.
